all:server client
server:server.cpp
	g++ server.cpp -o server -std=c++11 -Wall -Wextra -pedantic -g3
client:client.cpp
	g++ client.cpp -o client -std=c++11 -Wall -Wextra -pedantic -g3
clean:
	rm server client 
