all:server.cpp client.cpp
	g++ server.cpp -o server -std=c++11 -Wall -Wextra -pedantic -g3
	g++ client.cpp -o client -std=c++11 -Wall -Wextra -pedantic -g3
server:server.cpp
	g++ server.cpp -o env1/server -std=c++11 -Wall -Wextra -pedantic -g3
client:client.cpp
	g++ client.cpp -o env2/client -std=c++11 -Wall -Wextra -pedantic -g3
	g++ client.cpp -o env3/client -std=c++11 -Wall -Wextra -pedantic -g3
	g++ client.cpp -o env4/client -std=c++11 -Wall -Wextra -pedantic -g3
clean:
	rm server client 
