all: sender1 receiver1 sender2 receiver2 sender3 receiver3
sender1:sender1.cpp
	g++ sender1.cpp -o sender1 -std=c++14 -Wall -Wextra -pedantic -g3
receiver1: receiver1.cpp
	g++ receiver1.cpp -o receiver1 -std=c++14 -Wall -Wextra -pedantic -g3
sender2:sender2.cpp
	g++ sender2.cpp -o sender2 -std=c++14 -Wall -Wextra -pedantic -g3
receiver2:receiver2.cpp
	g++ receiver2.cpp -o receiver2 -std=c++14 -Wall -Wextra -pedantic -g3
sender3:sender3.cpp
	g++ sender3.cpp -o sender3 -std=c++14 -Wall -Wextra -pedantic -g3
receiver3:receiver3.cpp
	g++ receiver3.cpp -o receiver3 -std=c++14 -Wall -Wextra -pedantic -g3
clean:
	rm sender1 receiver1 sender2 receiver2 sender3 receiver3
